name: Build FlameCord with Maven

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java and Maven
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Get submodules
      run: |
        git submodule sync
        git submodule update --init --recursive

    - name: Build FlameCord
      run: ./flamecord build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FlameCord
        path: FlameCord-Proxy/bootstrap/target/FlameCord.jar
